configs:
  params:
    server.insecure: true

controller:
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 760m
      memory: 640Mi

repoServer:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 160Mi

server:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi