apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: argocd-application-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: argocd-application-controller
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: argocd-repo-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: argocd-repo-server
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: argocd-server
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: prometheus
  namespace: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: prometheus-kube-prometheus-stack-prometheus
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: grafana
  namespace: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: kube-prometheus-stack-grafana
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: loki
  namespace: loki
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: loki
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: foundry-pf2e
  namespace: foundry-vtt
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: foundry-pf2e
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: foundry-dstrahd
  namespace: foundry-vtt
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: foundry-dstrahd
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: foundry-unlit
  namespace: foundry-vtt
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: foundry-unlit
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: audiobookshelf
  updatePolicy:
    updateMode: "Off"
